import org.scalatest.matchers.should.Matchers
import org.scalatest.featurespec.AnyFeatureSpec

class QuarterlySpiritsQuestionsChangeLinksCYAPageSpec extends AnyFeatureSpec with Matchers {

  Feature("Quarterly Spirits Journey - Change Links - CYA Page") {

    Scenario("1. To verify the change link functionality at Check Your Answers page - Quarterly Spirits Journey") {
      ("I cleared the data for the service")
      ("I navigate to the Auth Login Stub Page")
      ("I enter redirect URL on Auth Login Stub Page for Alcohol Duty Service")
      ("I select Affinity Type as Organisation on Auth Login Stub Page")
      ("I enter Enrollment Key HMRC-AD-ORG, Identifier Name APPAID  Identifier Value AABCP0000100208 on Auth Login Stub Page")
      ("I click submit button on Auth Login Stub Page")
      ("I am presented with the Before You Start Page")
      ("I click continue button on Before You Start Page")
      ("I am presented with the Task List Page")
      ("I click on Tell us about spirits produced in the past three months hyperlink on Task List Page")
      ("I am presented with the Quarterly Spirits Returns Guidance Page")
      ("I select radio button Yes on Quarterly Spirits Returns Guidance Page")
      ("I click save  continue button on Quarterly Spirits Returns Guidance Page")
      ("I am presented with the Total Of All Spirits Page")
      ("I enter 111.11 on Total Of All Spirits Page")
      ("I click save  continue button on Total Of All Spirits Page")
      ("I am presented with the Declare Whiskey Page")
      ("I enter 222.22 for Scotch Whisky on Declare Whiskey Page")
      ("I enter 333.33 for Irish Whiskey on Declare Whiskey Page")
      ("I click save  continue button on Declare Whiskey Page")
      ("I am presented with the Which Of These Spirits Have You Produced Page")
      ("I select checkbox Malt spirits,Neutral spirits of agricultural origin,Spirits produced from beer,Other spirits on Which Of These Spirits Have You Produced Page")
      ("I click save  continue button on Which Of These Spirits Have You Produced Page")
      ("I am presented with the Declare Other Spirits Produced Page")
      ("I enter Test Spirits on Declare Other Spirits Produced Page")
      ("I click save  continue button on Declare Other Spirits Produced Page")
      ("I am presented with the Quarterly Spirits Check Your Answers Page")
      ("I click Change total of all spirits on Quarterly Spirits Check Your Answers Page")
      ("I am presented with the Total Of All Spirits Page with new url")
      ("I enter 111.99 on Total Of All Spirits Page")
      ("I click save  continue button on Total Of All Spirits Page")
      ("I am presented with the Quarterly Spirits Check Your Answers Page")
      ("I click Change Scotch Whisky on Quarterly Spirits Check Your Answers Page")
      ("I am presented with the Declare Whiskey Page with new url")
      ("I enter 222.99 for Scotch Whisky on Declare Whiskey Page")
      ("I enter 333.99 for Irish Whiskey on Declare Whiskey Page")
      ("I click save  continue button on Declare Whiskey Page")
      ("I am presented with the Quarterly Spirits Check Your Answers Page")
      ("I click Change type of spirits on Quarterly Spirits Check Your Answers Page")
      ("I am presented with the Which Of These Spirits Have You Produced Page with new url")
      ("I select checkbox Grain spirits on Which Of These Spirits Have You Produced Page")
      ("I click save  continue button on Which Of These Spirits Have You Produced Page")
      ("I am presented with the Quarterly Spirits Check Your Answers Page")
      ("I click Change other spirits produced on Quarterly Spirits Check Your Answers Page")
      ("I am presented with the Declare Other Spirits Produced Page with new url")
      ("I enter Test Spirits1 on Declare Other Spirits Produced Page")
      ("I click save  continue button on Declare Other Spirits Produced Page")
      ("I am presented with the Quarterly Spirits Check Your Answers Page")
      ("I click Change type of spirits on Quarterly Spirits Check Your Answers Page")
      ("I am presented with the Which Of These Spirits Have You Produced Page with new url")
      ("I select checkbox Other spirits on Which Of These Spirits Have You Produced Page")
      ("I click save  continue button on Which Of These Spirits Have You Produced Page")
      ("I am presented with the Quarterly Spirits Check Your Answers Page")
      ("I click save  continue button on Quarterly Spirits Check Your Answers Page")
      ("I am presented with the Task List Page")
    }
  }
}
