import org.scalatest.matchers.should.Matchers
import org.scalatest.featurespec.AnyFeatureSpec

class DutySuspendedDeliveriesSpec extends AnyFeatureSpec with Matchers {

  Feature("Alcohol Duty Return - Duty Suspended Deliveries - Change Link Functionality") {

    Scenario("1. Declare Duty Suspended Deliveries - Verify 'Change' links at Check your answer page") {
      ("I cleared the data for the service")
      ("I navigate to the Auth Login Stub Page")
      ("I enter redirect URL on Auth Login Stub Page for Alcohol Duty Service")
      ("I select Affinity Type as Organisation on Auth Login Stub Page")
      ("I enter Enrollment Key HMRC-AD-ORG, Identifier Name APPAID  Identifier Value AABCP0000100208 on Auth Login Stub Page")
      ("I click submit button on Auth Login Stub Page")
      ("I am presented with the Before You Start Page")
      ("I click continue button on Before You Start Page")
      ("I am presented with the Task List Page")
      ("I click on Tell us if you have delivered or received finished products in duty suspense hyperlink on Task List Page")
      ("I am presented with the Declare Duty Suspended Deliveries Page")
      ("I select radio button Yes on Declare Duty Suspended Deliveries Page")
      ("I click save  continue button on Declare Duty Suspended Deliveries Page")
      ("I am presented with the Duty Suspended Deliveries Guidance Page")
      ("I click continue button on Duty Suspended Deliveries Guidance Page")
      ("I am presented with the Duty Suspended Beer Page")
      ("I enter 2000.75 for Total Beer on Duty Suspended Beer Page")
      ("I enter 150.55 for Pure Alcohol In Beer on Duty Suspended Beer Page")
      ("I click save  continue button on Duty Suspended Beer Page")
      ("I am presented with the Duty Suspended Cider Page")
      ("I enter 9999.99 for Total Cider on Duty Suspended Cider Page")
      ("I enter 99.19 for Pure Alcohol In Cider on Duty Suspended Cider Page")
      ("I click save  continue button on Duty Suspended Cider Page")
      ("I am presented with the Duty Suspended Wine Page")
      ("I enter 7777.77 for Total Wine on Duty Suspended Wine Page")
      ("I enter 77.77 for Pure Alcohol In Wine on Duty Suspended Wine Page")
      ("I click save  continue button on Duty Suspended Wine Page")
      ("I am presented with the Duty Suspended Spirits Page")
      ("I enter 2100.75 for Total Spirits on Duty Suspended Spirits Page")
      ("I enter 160.55 for Pure Alcohol In Spirits on Duty Suspended Spirits Page")
      ("I click save  continue button on Duty Suspended Spirits Page")
      ("I am presented with the Duty Suspended Other Fermented Products Page")
      ("I enter 8888.88 for Total Other Fermented Products on Duty Suspended Other Fermented Products Page")
      ("I enter 88.88 for Pure Alcohol In Other Fermented Products on Duty Suspended Other Fermented Products Page")
      ("I click save  continue button on Duty Suspended Other Fermented Products Page")
      ("I am presented with the Duty Suspended Deliveries Check Your Answers Page")
      ("I click Change total net quantity of duty suspended beer on Duty Suspended Deliveries Check Your Answers Page")
      ("I am presented with the Duty Suspended Beer Page with new url")
      ("I enter 3000.75 for Total Beer on Duty Suspended Beer Page")
      ("I enter 250.55 for Pure Alcohol In Beer on Duty Suspended Beer Page")
      ("I click save  continue button on Duty Suspended Beer Page")
      ("I am presented with the Duty Suspended Deliveries Check Your Answers Page")
      ("I click Change total net quantity of pure alcohol in your duty suspended cider on Duty Suspended Deliveries Check Your Answers Page")
      ("I am presented with the Duty Suspended Cider Page with new url")
      ("I enter 1500.35 for Total Cider on Duty Suspended Cider Page")
      ("I enter 300.55 for Pure Alcohol In Cider on Duty Suspended Cider Page")
      ("I click save  continue button on Duty Suspended Cider Page")
      ("I am presented with the Duty Suspended Deliveries Check Your Answers Page")
      ("I click Change total net quantity of pure alcohol in your duty suspended wine on Duty Suspended Deliveries Check Your Answers Page")
      ("I am presented with the Duty Suspended Wine Page with new url")
      ("I enter 2800.35 for Total Wine on Duty Suspended Wine Page")
      ("I enter 160.65 for Pure Alcohol In Wine on Duty Suspended Wine Page")
      ("I click save  continue button on Duty Suspended Wine Page")
      ("I am presented with the Duty Suspended Deliveries Check Your Answers Page")
      ("I click Change total net quantity of pure alcohol in your duty suspended spirits on Duty Suspended Deliveries Check Your Answers Page")
      ("I am presented with the Duty Suspended Spirits Page with new url")
      ("I enter 7800.35 for Total Spirits on Duty Suspended Spirits Page")
      ("I enter 460.65 for Pure Alcohol In Spirits on Duty Suspended Spirits Page")
      ("I click save  continue button on Duty Suspended Spirits Page")
      ("I am presented with the Duty Suspended Deliveries Check Your Answers Page")
      ("I click Change total net quantity of pure alcohol in your duty suspended other fermented products on Duty Suspended Deliveries Check Your Answers Page")
      ("I am presented with the Duty Suspended Other Fermented Products Page with new url")
      ("I enter 8800.35 for Total Other Fermented Products on Duty Suspended Other Fermented Products Page")
      ("I enter 560.65 for Pure Alcohol In Other Fermented Products on Duty Suspended Other Fermented Products Page")
      ("I click save  continue button on Duty Suspended Other Fermented Products Page")
      ("I am presented with the Duty Suspended Deliveries Check Your Answers Page")
      ("I click continue button on Duty Suspended Deliveries Check Your Answers Page")
      ("I am presented with the Task List Page")
    }
  }
}
