import org.scalatest.matchers.should.Matchers
import org.scalatest.featurespec.AnyFeatureSpec

class AlcoholDutyReturnsChangeLinksCYAPageSpec extends AnyFeatureSpec with Matchers {

  Feature("Alcohol Duty Returns Journey - Change Links - CYA Page") {

    Scenario("Beer- Alcohol Duty Returns Journey -  Multiple SPR is set to 'Yes' - Change link functionality") {
      ("I click on Declare beer hyperlink on Task List Page")
      ("I am presented with the What Do You Need To Declare Beer Page")
      ("I select checkbox Beer between 1.3%  3.4% ABV (tax type code 311),Beer between 3.5%  8.4% ABV (tax type code 321),Beer between 8.5%  22% ABV (tax type code 331),Beer at or above 22.1% ABV (tax type code 341),Beer between 1.3%  3.4% ABV (tax type code 351),Beer between 3.5%  8.4% ABV (tax type code 356),Beer between 1.3%  3.4% ABV (tax type code 361 SPR),Beer between 3.5%  8.4% ABV (tax type code 366 SPR),Beer between 1.3%  3.4% ABV (tax type code 371 SPR),Beer between 3.5%  8.4% ABV (tax type code 376 SPR) on What Do You Need To Declare Beer Page")
      ("I click save  continue button on What Do You Need To Declare Beer Page")
      ("I am presented with the How Much You Need To Declare Beer Page")
      ("I enter 945.55 for Stard beer between 1.3%  3.4% ABV - Total litres on How Much You Need To Declare Beer Page at first input box")
      ("I enter 55.5500 for Stard beer between 1.3%  3.4% ABV - Pure alcohol on How Much You Need To Declare Beer Page at first input box")
      ("I enter 898.34 for Stard beer between 3.5%  8.4% ABV - Total litres on How Much You Need To Declare Beer Page at second input box")
      ("I enter 77.5500 for Stard beer between 3.5%  8.4% ABV - Pure alcohol on How Much You Need To Declare Beer Page at second input box")
      ("I enter 667.32 for Stard beer between 8.5%  22% ABV - Total litres on How Much You Need To Declare Beer Page at third input box")
      ("I enter 66.3400 for Stard beer between 8.5%  22% ABV - Pure alcohol on How Much You Need To Declare Beer Page at third input box")
      ("I enter 999.19 for Stard beer at or above 22.1% ABV - Total litres on How Much You Need To Declare Beer Page at fourth input box")
      ("I enter 99.1300 for Stard beer at or above 22.1% ABV - Pure alcohol on How Much You Need To Declare Beer Page at fourth input box")
      ("I enter 887.54 for Draught beer between 1.3%  3.4% ABV - Total litres on How Much You Need To Declare Beer Page at fifth input box")
      ("I enter 66.4400 for Draught beer between 1.3%  3.4% ABV - Pure alcohol on How Much You Need To Declare Beer Page at fifth input box")
      ("I enter 699.45 for Draught beer between 3.5%  8.4% ABV - Total litres on How Much You Need To Declare Beer Page at sixth input box")
      ("I enter 66.8900 for Draught beer between 3.5%  8.4% ABV - Pure alcohol on How Much You Need To Declare Beer Page at sixth input box")
      ("I click save  continue button on How Much You Need To Declare Beer Page")
      ("I am presented with the Do You Have Multiple Small Producer Relief Duty Rate Beer Page")
      ("I select radio button Yes on Do You Have Multiple Small Producer Relief Duty Rate Beer Page")
      ("I click save  continue button on Do You Have Multiple Small Producer Relief Duty Rate Beer Page")
      ("I am presented with the Multiple Small Producer Relief Rate Beer Page")
      ("I select radio button Non-draught beer between 1.3%  3.4% ABV (361 SPR) on Multiple Small Producer Relief Rate Beer Page")
      ("I enter 9999.99 for Total litres on Multiple Small Producer Relief Rate Beer Page")
      ("I enter 89.9900 for Litres of pure alcohol on Multiple Small Producer Relief Rate Beer Page")
      ("I enter 19 for Duty rate on Multiple Small Producer Relief Rate Beer Page")
      ("I click save  continue button on Multiple Small Producer Relief Rate Beer Page")
      ("I am presented with the Check Your Answers SPR Beer Page")
      ("I click Change Description on Check Your Answers SPR Beer Page")
      ("I am presented with the Multiple Small Producer Relief Rate Beer Page with url suffix as #taxType")
      ("I click save  continue button on Multiple Small Producer Relief Rate Beer Page")
      ("I am presented with the Check Your Answers SPR Beer Page")
      ("I click Change Description on Check Your Answers SPR Beer Page")
      ("I am presented with the Multiple Small Producer Relief Rate Beer Page with url suffix as #taxType")
      ("I select radio button Non-draught beer between 3.5%  8.4% ABV (366 SPR) on Multiple Small Producer Relief Rate Beer Page")
      ("I click save  continue button on Multiple Small Producer Relief Rate Beer Page")
      ("I am presented with the Check Your Answers SPR Beer Page")
      ("I click continue button on Check Your Answers SPR Beer Page")
      ("I am presented with the Multiple SPR List Question Beer Page")
      ("I click Change hyperlink on Multiple SPR List Question Beer Page")
      ("I am presented with the Multiple Small Producer Relief Rate Beer Page with existing url suffix as ?index=0")
      ("I select radio button Draught beer between 1.3%  3.4% ABV (371 SPR) on Multiple Small Producer Relief Rate Beer Page")
      ("I enter 8888.88 for Total litres on Multiple Small Producer Relief Rate Beer Page")
      ("I enter 88.8800 for Litres of pure alcohol on Multiple Small Producer Relief Rate Beer Page")
      ("I enter 22 for Duty rate on Multiple Small Producer Relief Rate Beer Page")
      ("I click save  continue button on Multiple Small Producer Relief Rate Beer Page")
      ("I am presented with the Check Your Answers SPR Beer Page with url suffix as ?index=0")
      ("I click continue button on Check Your Answers SPR Beer Page")
      ("I am presented with the Multiple SPR List Question Beer Page")
      ("I select radio button No on Multiple SPR List Question Beer Page")
      ("I click save  continue button on Multiple SPR List Question Beer Page")
      ("I am presented with the You Have Some Missing Details Page")
      ("I select radio button Delete these declarations from this return on You Have Some Missing Details Page")
      ("I click save  continue button on You Have Some Missing Details Page")
      ("I am presented with the Are You Sure You Want To Delete These Declarations From Your Return Page")
      ("I select radio button Yes, delete these declarations on Are You Sure You Want To Delete These Declarations From Your Return Page")
      ("I click confirm  continue button on Are You Sure You Want To Delete These Declarations From Your Return Page")
      ("I am presented with the Check Your Answers Returns Beer Page")
    }

    Scenario("Cider- Alcohol Duty Returns Journey -  Multiple SPR is set to 'No' - Change link functionality") {
      ("I click on Declare cider hyperlink on Task List Page")
      ("I am presented with the What Do You Need To Declare Cider Page")
      ("I select checkbox Cider between 1.3%  3.4% ABV (tax type code 312),Cider between 3.5%  8.4% ABV  sparkling cider between 3.5%  5.5% ABV (tax type code 322),Sparkling cider between 5.6%  8.4% ABV (tax type code 324),Cider between 1.3%  3.4% ABV (tax type code 352),Cider between 3.5%  8.4% ABV  sparkling cider between 3.5%  5.5% ABV (tax type code 357),Sparkling cider between 5.6%  8.4% ABV (tax type code 359),Cider between 1.3%  3.4% ABV (tax type code 362 SPR),Cider between 3.5%  8.4% ABV  sparkling cider between 3.5%  5.5% ABV (tax type code 367 SPR),Sparkling cider between 5.6%  8.4% ABV (tax type code 369 SPR),Cider between 1.3%  3.4% ABV (tax type code 372 SPR),Cider between 3.5%  8.4% ABV  sparkling cider between 3.5%  5.5% ABV (tax type code 377 SPR),Sparkling cider between 5.6%  8.4% ABV (tax type code 379 SPR) on What Do You Need To Declare Cider Page")
      ("I click save  continue button on What Do You Need To Declare Cider Page")
      ("I am presented with the How Much You Need To Declare Cider Page")
      ("I enter 789.44 for Stard cider between 1.3%  3.4% ABV - Total litres on How Much You Need To Declare Cider Page at first input box")
      ("I enter 43.4400 for Stard cider between 1.3%  3.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at first input box")
      ("I enter 898.12 for Stard cider between 3.5%  8.4% ABV - Total litres on How Much You Need To Declare Cider Page at second input box")
      ("I enter 22.2200 for Stard cider between 3.5%  8.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at second input box")
      ("I enter 999.99 for Stard sparkling between 5.6%  8.4% ABV - Total litres on How Much You Need To Declare Cider Page at third input box")
      ("I enter 99.9900 for Stard sparkling between 5.6%  8.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at third input box")
      ("I enter 787.77 for Draught cider between 1.3%  3.4% ABV - Total litres on How Much You Need To Declare Cider Page at fourth input box")
      ("I enter 33.2100 for Draught cider between 1.3%  3.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at fourth input box")
      ("I enter 889.12 for Draught cider between 3.5%  8.4% ABV - Total litres on How Much You Need To Declare Cider Page at fifth input box")
      ("I enter 22.4500 for Draught cider between 3.5%  8.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at fifth input box")
      ("I enter 888.88 for Draught sparkling cider between 5.6%  8.4% ABV - Total litres on How Much You Need To Declare Cider Page at sixth input box")
      ("I enter 888.8800 for Draught sparkling cider between 5.6%  8.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at sixth input box")
      ("I click save  continue button on How Much You Need To Declare Cider Page")
      ("I am presented with the Do You Have Multiple Small Producer Relief Duty Rate Cider Page")
      ("I select radio button No on Do You Have Multiple Small Producer Relief Duty Rate Cider Page")
      ("I click save  continue button on Do You Have Multiple Small Producer Relief Duty Rate Cider Page")
      ("I am presented with the Single Small Producer Relief Rate Cider Page")
      ("I enter 656.66 for Non-draught cider between 1.3%  3.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at first input box")
      ("I enter 66.6600 for Non-draught cider between 1.3%  3.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at first input box")
      ("I enter 14 for Non-draught cider between 1.3%  3.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at first input box")
      ("I enter 999.99 for Non-draught cider between 3.5%  8.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at second input box")
      ("I enter 98.9900 for Non-draught cider between 3.5%  8.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at second input box")
      ("I enter 12.45 for Non-draught cider between 3.5%  8.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at second input box")
      ("I enter 6666.66 for Non-draught sparkling cider between 5.6%  8.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at third input box")
      ("I enter 666.6600 for Non-draught sparkling cider between 5.6%  8.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at third input box")
      ("I enter 36 for Non-draught sparkling cider between 5.6%  8.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at third input box")
      ("I enter 887.21 for Draught cider between 1.3%  3.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at fourth input box")
      ("I enter 45.5600 for Draught cider between 1.3%  3.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at fourth input box")
      ("I enter 16 for Draught cider between 1.3%  3.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at fourth input box")
      ("I enter 653.11 for Draught cider between 3.5%  8.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at fifth input box")
      ("I enter 33.3300 for Draught cider between 3.5%  8.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at fifth input box")
      ("I enter 18 for Draught cider between 3.5%  8.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at fifth input box")
      ("I enter 777.77 for Draught sparkling cider between 5.6%  8.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at sixth input box")
      ("I enter 77.7700 for Draught sparkling cider between 5.6%  8.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at sixth input box")
      ("I enter 17 for Draught sparkling cider between 5.6%  8.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at sixth input box")
      ("I click save  continue button on Single Small Producer Relief Rate Cider Page")
      ("I am presented with the Check Your Answers Returns Cider Page")
      ("I click Change Cider to declare on Check Your Answers Returns Cider Page")
      ("I am presented with the What Do You Need To Declare Cider Page with new url")
      ("I click save  continue button on What Do You Need To Declare Cider Page")
      ("I am presented with the Check Your Answers Returns Cider Page")
      ("I click Change Cider to declare on Check Your Answers Returns Cider Page")
      ("I am presented with the What Do You Need To Declare Cider Page with new url")
      ("I unselect checkbox Sparkling cider between 5.6%  8.4% ABV (tax type code 359) on What Do You Need To Declare Cider Page")
      ("I click save  continue button on What Do You Need To Declare Cider Page")
      ("I am presented with the How Much You Need To Declare Cider Page")
      ("I enter 789.44 for Stard cider between 1.3%  3.4% ABV - Total litres on How Much You Need To Declare Cider Page at first input box")
      ("I enter 43.4400 for Stard cider between 1.3%  3.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at first input box")
      ("I enter 898.12 for Stard cider between 3.5%  8.4% ABV - Total litres on How Much You Need To Declare Cider Page at second input box")
      ("I enter 22.2200 for Stard cider between 3.5%  8.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at second input box")
      ("I enter 999.99 for Stard sparkling between 5.6%  8.4% ABV - Total litres on How Much You Need To Declare Cider Page at third input box")
      ("I enter 99.9900 for Stard sparkling between 5.6%  8.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at third input box")
      ("I enter 787.77 for Draught cider between 1.3%  3.4% ABV - Total litres on How Much You Need To Declare Cider Page at fourth input box")
      ("I enter 33.2100 for Draught cider between 1.3%  3.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at fourth input box")
      ("I enter 889.12 for Draught cider between 3.5%  8.4% ABV - Total litres on How Much You Need To Declare Cider Page at fifth input box")
      ("I enter 22.4500 for Draught cider between 3.5%  8.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at fifth input box")
      ("I click save  continue button on How Much You Need To Declare Cider Page")
      ("I am presented with the Do You Have Multiple Small Producer Relief Duty Rate Cider Page")
      ("I select radio button No on Do You Have Multiple Small Producer Relief Duty Rate Cider Page")
      ("I click save  continue button on Do You Have Multiple Small Producer Relief Duty Rate Cider Page")
      ("I am presented with the Single Small Producer Relief Rate Cider Page")
      ("I enter 656.66 for Non-draught cider between 1.3%  3.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at first input box")
      ("I enter 66.6600 for Non-draught cider between 1.3%  3.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at first input box")
      ("I enter 14 for Non-draught cider between 1.3%  3.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at first input box")
      ("I enter 999.99 for Non-draught cider between 3.5%  8.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at second input box")
      ("I enter 98.9900 for Non-draught cider between 3.5%  8.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at second input box")
      ("I enter 12.45 for Non-draught cider between 3.5%  8.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at second input box")
      ("I enter 6666.66 for Non-draught sparkling cider between 5.6%  8.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at third input box")
      ("I enter 666.6600 for Non-draught sparkling cider between 5.6%  8.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at third input box")
      ("I enter 36 for Non-draught sparkling cider between 5.6%  8.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at third input box")
      ("I enter 887.21 for Draught cider between 1.3%  3.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at fourth input box")
      ("I enter 45.5600 for Draught cider between 1.3%  3.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at fourth input box")
      ("I enter 16 for Draught cider between 1.3%  3.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at fourth input box")
      ("I enter 653.11 for Draught cider between 3.5%  8.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at fifth input box")
      ("I enter 33.3300 for Draught cider between 3.5%  8.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at fifth input box")
      ("I enter 18 for Draught cider between 3.5%  8.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at fifth input box")
      ("I enter 777.77 for Draught sparkling cider between 5.6%  8.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at sixth input box")
      ("I enter 77.7700 for Draught sparkling cider between 5.6%  8.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at sixth input box")
      ("I enter 17 for Draught sparkling cider between 5.6%  8.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at sixth input box")
      ("I click save  continue button on Single Small Producer Relief Rate Cider Page")
      ("I am presented with the Check Your Answers Returns Cider Page")
      ("I click Change Cider duty on Check Your Answers Returns Cider Page")
      ("I am presented with the How Much You Need To Declare Cider Page with new url")
      ("I click save  continue button on How Much You Need To Declare Cider Page")
      ("I am presented with the Check Your Answers Returns Cider Page")
      ("I click Change Cider duty on Check Your Answers Returns Cider Page")
      ("I am presented with the How Much You Need To Declare Cider Page with new url")
      ("I enter 999.99 for Stard cider between 1.3%  3.4% ABV - Total litres on How Much You Need To Declare Cider Page at first input box")
      ("I enter 99.9900 for Stard cider between 1.3%  3.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at first input box")
      ("I click save  continue button on How Much You Need To Declare Cider Page")
      ("I am presented with the Check Your Answers Returns Cider Page")
      ("I click Change Cider eligible for Small Producer Relief on Check Your Answers Returns Cider Page")
      ("I am presented with the Single Small Producer Relief Rate Cider Page with new url")
      ("I click save  continue button on Single Small Producer Relief Rate Cider Page")
      ("I am presented with the Check Your Answers Returns Cider Page")
      ("I click Change Cider eligible for Small Producer Relief on Check Your Answers Returns Cider Page")
      ("I am presented with the Single Small Producer Relief Rate Cider Page with new url")
      ("I enter 777.77 for Draught cider between 1.3%  3.4% ABV - Total litres on Single Small Producer Relief Rate Cider Page at third input box")
      ("I enter 77.7700 for Draught cider between 1.3%  3.4% ABV - Pure alcohol litres on Single Small Producer Relief Rate Cider Page at third input box")
      ("I enter 7.7 for Draught cider between 1.3%  3.4% ABV - SPR Rate on Single Small Producer Relief Rate Cider Page at third input box")
      ("I click save  continue button on Single Small Producer Relief Rate Cider Page")
      ("I am presented with the Check Your Answers Returns Cider Page")
      ("I click save  continue button on Check Your Answers Returns Cider Page")
      ("I am presented with the Duty Due Cider Page")
      ("I click on change link 3 on Duty Due Cider Page for alcohol type Cider")
      ("I am presented with the Check Your Answers Returns Cider Page")
      ("I click save  continue button on Check Your Answers Returns Cider Page")
      ("I am presented with the Duty Due Cider Page")
      ("I click on change link 4 on Duty Due Cider Page for alcohol type Cider")
      ("I am presented with the Check Your Answers Returns Cider Page")
      ("I click save  continue button on Check Your Answers Returns Cider Page")
      ("I am presented with the Duty Due Cider Page")
    }

    Scenario("To verify the change link functionalities from the Return Summary Page") {
      ("I click on Declare beer hyperlink on Task List Page")
      ("I am presented with the What Do You Need To Declare Beer Page")
      ("I select checkbox Beer at or above 22.1% ABV (tax type code 341) on What Do You Need To Declare Beer Page")
      ("I click save  continue button on What Do You Need To Declare Beer Page")
      ("I am presented with the How Much You Need To Declare Beer Page")
      ("I enter 999.19 for Stard beer at or above 22.1% ABV - Total litres on How Much You Need To Declare Beer Page at first input box")
      ("I enter 99.1300 for Stard beer at or above 22.1% ABV - Pure alcohol on How Much You Need To Declare Beer Page at first input box")
      ("I click save  continue button on How Much You Need To Declare Beer Page")
      ("I am presented with the Check Your Answers Returns Beer Page")
      ("I click save  continue button on Check Your Answers Returns Beer Page")
      ("I am presented with the Duty Due Beer Page")
      ("I click save  continue button on Duty Due Beer Page")
      ("I am presented with the Task List Page")
      ("I click on Declare cider hyperlink on Task List Page")
      ("I am presented with the What Do You Need To Declare Cider Page")
      ("I select checkbox Cider between 1.3%  3.4% ABV (tax type code 312) on What Do You Need To Declare Cider Page")
      ("I click save  continue button on What Do You Need To Declare Cider Page")
      ("I am presented with the How Much You Need To Declare Cider Page")
      ("I enter 789.44 for Stard cider between 1.3%  3.4% ABV - Total litres on How Much You Need To Declare Cider Page at first input box")
      ("I enter 43.4400 for Stard cider between 1.3%  3.4% ABV - Pure alcohol on How Much You Need To Declare Cider Page at first input box")
      ("I click save  continue button on How Much You Need To Declare Cider Page")
      ("I am presented with the Check Your Answers Returns Cider Page")
      ("I click save  continue button on Check Your Answers Returns Cider Page")
      ("I am presented with the Duty Due Cider Page")
      ("I click save  continue button on Duty Due Cider Page")
      ("I am presented with the Task List Page")
      ("I click on Declare wine hyperlink on Task List Page")
      ("I am presented with the Declaring Your Wine For Duty")
      ("I click continue button on Declaring Your Wine For Duty")
      ("I am presented with the What Do You Need To Declare Wine Page")
      ("I select checkbox Wine between 1.3%  3.4% ABV (tax type code 313) on What Do You Need To Declare Wine Page")
      ("I click save  continue button on What Do You Need To Declare Wine Page")
      ("I am presented with the How Much You Need To Declare Wine Page")
      ("I enter 1234.55 for Stard wine between 1.3%  3.4% ABV - Total litres on How Much You Need To Declare Wine Page at first input box")
      ("I enter 35.5500 for Stard wine between 1.3%  3.4% ABV - Pure alcohol on How Much You Need To Declare Wine Page at first input box")
      ("I click save  continue button on How Much You Need To Declare Wine Page")
      ("I am presented with the Check Your Answers Returns Wine Page")
      ("I click save  continue button on Check Your Answers Returns Wine Page")
      ("I am presented with the Duty Due Wine Page")
      ("I click save  continue button on Duty Due Wine Page")
      ("I am presented with the Task List Page")
      ("I click on Declare spirits hyperlink on Task List Page")
      ("I am presented with the What Do You Need To Declare Spirits Page")
      ("I select checkbox Spirits between 1.3%  3.4% ABV (tax type code 315) on What Do You Need To Declare Spirits Page")
      ("I click save  continue button on What Do You Need To Declare Spirits Page")
      ("I am presented with the How Much You Need To Declare Spirits Page")
      ("I enter 8888.66 for Stard spirits between 1.3%  3.4% ABV - Total litres on How Much You Need To Declare Spirits Page at first input box")
      ("I enter 88.8000 for Stard spirits between 1.3%  3.4% ABV - Pure alcohol on How Much You Need To Declare Spirits Page at first input box")
      ("I click save  continue button on How Much You Need To Declare Spirits Page")
      ("I am presented with the Check Your Answers Returns Spirits Page")
      ("I click save  continue button on Check Your Answers Returns Spirits Page")
      ("I am presented with the Duty Due Spirits Page")
      ("I click save  continue button on Duty Due Spirits Page")
      ("I am presented with the Task List Page")
      ("I click on Declare other fermented products hyperlink on Task List Page")
      ("I am presented with the What Do You Need To Declare Other Fermented Product Page")
      ("I select checkbox Other fermented products between 1.3%  3.4% ABV (tax type code 314) on What Do You Need To Declare Wine Page")
      ("I click save  continue button on What Do You Need To Declare Other Fermented Product Page")
      ("I am presented with the How Much You Need To Declare Other Fermented Product Page")
      ("I enter 2233.33 for Stard other fermented products between 1.3%  3.4% ABV - Total litres on How Much You Need To Declare Other Fermented Product Page at first input box")
      ("I enter 33.3300 for Stard other fermented products between 1.3%  3.4% ABV - Pure alcohol on How Much You Need To Declare Other Fermented Product Page at first input box")
      ("I click save  continue button on How Much You Need To Declare Other Fermented Product Page")
      ("I am presented with the Check Your Answers Returns Other Fermented Product Page")
      ("I click save  continue button on Check Your Answers Returns Other Fermented Product Page")
      ("I am presented with the Duty Due Other Fermented Product Page")
      ("I click save  continue button on Duty Due Other Fermented Product Page")
      ("I am presented with the Task List Page")
      ("I click on Tell us if you have adjustments to declare hyperlink on Task List Page")
      ("I am presented with the Declare Adjustment Question Page")
      ("I select radio button Yes on Declare Adjustment Question Page")
      ("I click save  continue button on Declare Adjustment Question Page")
      ("I am presented with the Adjustment Type Page")
      ("I select radio button Under-declaration on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page")
      ("I enter month 09  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code Page")
      ("I enter 311 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume Page")
      ("I enter 123.45 for Total Litres on Adjustment Volume Page")
      ("I enter 5.5000 for Litres Of Pure Alcohol on Adjustment Volume Page")
      ("I click save  continue button on Adjustment Volume Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button Yes on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Adjustment Type Page")
      ("I select radio button Over-declaration on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page")
      ("I enter month 10  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code Page")
      ("I enter 312 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume Page")
      ("I enter 222.22 for Total Litres on Adjustment Volume Page")
      ("I enter 22.2200 for Litres Of Pure Alcohol on Adjustment Volume Page")
      ("I click save  continue button on Adjustment Volume Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button Yes on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Adjustment Type Page")
      ("I select radio button Repackaged draught products on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page")
      ("I enter month 11  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code For Repackaged Page")
      ("I enter 373 on Adjustment Tax Type Code For Repackaged Page")
      ("I click save  continue button on Adjustment Tax Type Code For Repackaged Page")
      ("I am presented with the Adjustment Volume With Spr Page")
      ("I enter 3000.75 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 9.8 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the New Tax Type Code Page")
      ("I enter 363 on New Tax Type Code Page")
      ("I click save  continue button on New Tax Type Code Page")
      ("I am presented with the New Spr Duty Rate Page")
      ("I enter 11.5 on New Spr Duty Rate Page")
      ("I click save  continue button on New Spr Duty Rate Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button Yes on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Adjustment Type Page")
      ("I select radio button Spoilt on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Spoilt Alcohol Type Page")
      ("I select radio button Spirits on Spoilt Alcohol Type Page")
      ("I click save  continue button on Spoilt Alcohol Type Page")
      ("I am presented with the Spoilt Alcohol Volume Page")
      ("I enter 3000.75 for Total Litres on Spoilt Alcohol Volume Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Spoilt Alcohol Volume Page")
      ("I enter 3255.55 for Duty Paid on Spoilt Alcohol Volume Page")
      ("I click save  continue button on Spoilt Alcohol Volume Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button Yes on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Adjustment Type Page")
      ("I select radio button Drawback on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page")
      ("I enter month 10  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code Page")
      ("I enter 314 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume Page")
      ("I enter 3000.75 for Total Litres on Adjustment Volume Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume Page")
      ("I click save  continue button on Adjustment Volume Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button No on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Task List Page")
      ("I click on Tell us if you have delivered or received finished products in duty suspense hyperlink on Task List Page")
      ("I am presented with the Declare Duty Suspended Deliveries Page")
      ("I select radio button Yes on Declare Duty Suspended Deliveries Page")
      ("I click save  continue button on Declare Duty Suspended Deliveries Page")
      ("I am presented with the Duty Suspended Deliveries Guidance Page")
      ("I click continue button on Duty Suspended Deliveries Guidance Page")
      ("I am presented with the Duty Suspended Beer Page")
      ("I enter 2000.75 for Total Beer on Duty Suspended Beer Page")
      ("I enter 150.55 for Pure Alcohol In Beer on Duty Suspended Beer Page")
      ("I click save  continue button on Duty Suspended Beer Page")
      ("I am presented with the Duty Suspended Cider Page")
      ("I enter 9999.99 for Total Cider on Duty Suspended Cider Page")
      ("I enter 99.19 for Pure Alcohol In Cider on Duty Suspended Cider Page")
      ("I click save  continue button on Duty Suspended Cider Page")
      ("I am presented with the Duty Suspended Wine Page")
      ("I enter 7777.77 for Total Wine on Duty Suspended Wine Page")
      ("I enter 77.77 for Pure Alcohol In Wine on Duty Suspended Wine Page")
      ("I click save  continue button on Duty Suspended Wine Page")
      ("I am presented with the Duty Suspended Spirits Page")
      ("I enter 2100.75 for Total Spirits on Duty Suspended Spirits Page")
      ("I enter 160.55 for Pure Alcohol In Spirits on Duty Suspended Spirits Page")
      ("I click save  continue button on Duty Suspended Spirits Page")
      ("I am presented with the Duty Suspended Other Fermented Products Page")
      ("I enter 8888.88 for Total Other Fermented Products on Duty Suspended Other Fermented Products Page")
      ("I enter 88.88 for Pure Alcohol In Other Fermented Products on Duty Suspended Other Fermented Products Page")
      ("I click save  continue button on Duty Suspended Other Fermented Products Page")
      ("I am presented with the Duty Suspended Deliveries Check Your Answers Page")
      ("I click continue button on Duty Suspended Deliveries Check Your Answers Page")
      ("I am presented with the Task List Page")
      ("I click on Tell us about spirits produced in the past three months hyperlink on Task List Page")
      ("I am presented with the Quarterly Spirits Returns Guidance Page")
      ("I select radio button Yes on Quarterly Spirits Returns Guidance Page")
      ("I click save  continue button on Quarterly Spirits Returns Guidance Page")
      ("I am presented with the Total Of All Spirits Page")
      ("I enter 99 on Total Of All Spirits Page")
      ("I click save  continue button on Total Of All Spirits Page")
      ("I am presented with the Declare Whiskey Page")
      ("I enter 10.55 for Scotch Whisky on Declare Whiskey Page")
      ("I enter 20.67 for Irish Whiskey on Declare Whiskey Page")
      ("I click save  continue button on Declare Whiskey Page")
      ("I am presented with the Which Of These Spirits Have You Produced Page")
      ("I select checkbox Malt spirits,Neutral spirits of agricultural origin,Spirits produced from beer,Other spirits on Which Of These Spirits Have You Produced Page")
      ("I click save  continue button on Which Of These Spirits Have You Produced Page")
      ("I am presented with the Declare Other Spirits Produced Page")
      ("I enter Test Spirits on Declare Other Spirits Produced Page")
      ("I click save  continue button on Declare Other Spirits Produced Page")
      ("I am presented with the Quarterly Spirits Check Your Answers Page")
      ("I click save  continue button on Quarterly Spirits Check Your Answers Page")
      ("I am presented with the Task List Page")
      ("I click on Check duty payable  send your return hyperlink on Task List Page")
      ("I am presented with the Return Summary Page")
      ("I click Change Declared spirits duty on Return Summary Page")
      ("I am presented with the Check Your Answers Returns Spirits Page")
      ("I enter redirect url for Return Summary Page")
      ("I am presented with the Return Summary Page")
      ("I click Change Declared wine duty on Return Summary Page")
      ("I am presented with the Check Your Answers Returns Wine Page")
      ("I enter redirect url for Return Summary Page")
      ("I am presented with the Return Summary Page")
      ("I click Change Declared cider duty on Return Summary Page")
      ("I am presented with the Check Your Answers Returns Cider Page")
      ("I enter redirect url for Return Summary Page")
      ("I am presented with the Return Summary Page")
      ("I click Change Declared other fermented products duty on Return Summary Page")
      ("I am presented with the Check Your Answers Returns Other Fermented Product Page")
      ("I enter redirect url for Return Summary Page")
      ("I am presented with the Return Summary Page")
      ("I click Change Declared beer duty on Return Summary Page")
      ("I am presented with the Check Your Answers Returns Beer Page")
      ("I enter redirect url for Return Summary Page")
      ("I am presented with the Return Summary Page")
      ("I click Change Adjustment duty value on Return Summary Page")
      ("I am presented with the Adjustment List Page")
      ("I enter redirect url for Return Summary Page")
      ("I am presented with the Return Summary Page")
      ("I click Change Duty suspended alcohol on Return Summary Page")
      ("I am presented with the Duty Suspended Deliveries Check Your Answers Page")
      ("I enter redirect url for Return Summary Page")
      ("I am presented with the Return Summary Page")
      ("I click Change Spirits production on Return Summary Page")
      ("I am presented with the Quarterly Spirits Check Your Answers Page")
      ("I enter redirect url for Return Summary Page")
      ("I am presented with the Return Summary Page")
    }
  }
}
