import org.scalatest.matchers.should.Matchers
import org.scalatest.featurespec.AnyFeatureSpec

class AdjustmentsJourneyChangeLinksCYAPageSpec extends AnyFeatureSpec with Matchers {

  Feature("Adjustments Journey - Change Links - CYA Page") {

    Scenario("1- Adjustments Journey - Change Link Functionality for Adjustment Type - Under-declaration - Beer") {
      ("I select radio button Under-declaration on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page")
      ("I enter month 09  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code Page")
      ("I enter 311 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume Page")
      ("I enter 3000.75 for Total Litres on Adjustment Volume Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume Page")
      ("I click save  continue button on Adjustment Volume Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click Adjustment on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment Type Page with new url")
      ("I select radio button Over-declaration on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page with new url")
      ("I enter month 09  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code Page with new url")
      ("I enter 371 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume With Spr Page with new url")
      ("I enter 3000.75 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 9.8 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button No on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Task List Page")
    }

    Scenario("2- Adjustments Journey - Change Link Functionality for Return period being adjusted  Tax Type  SPR Duty Rate - Over-declaration - Cider") {
      ("I select radio button Over-declaration on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page")
      ("I enter month 10  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code Page")
      ("I enter 372 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume With Spr Page")
      ("I enter 3000.75 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 9.8 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click Return period being adjusted on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment Return Date Page with new url")
      ("I enter month 12  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code Page with new url")
      ("I enter 372 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume With Spr Page with new url")
      ("I enter 3000.75 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 10.5 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click Tax type on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment Tax Type Code Page with new url")
      ("I enter 374 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume With Spr Page with new url")
      ("I enter 3000.75 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 10.5 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click SPR duty rate on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment Volume With Spr Page with new url")
      ("I enter 12.5 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button No on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Task List Page")
    }

    Scenario("3- Adjustments Journey - Change Link Functionality for Volume  New Tax Type - Repackaged Draught Products - Wine") {
      ("I select radio button Repackaged draught products on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page")
      ("I enter month 11  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code For Repackaged Page")
      ("I enter 373 on Adjustment Tax Type Code For Repackaged Page")
      ("I click save  continue button on Adjustment Tax Type Code For Repackaged Page")
      ("I am presented with the Adjustment Volume With Spr Page")
      ("I enter 3000.75 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 9.8 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the New Tax Type Code Page")
      ("I enter 363 on New Tax Type Code Page")
      ("I click save  continue button on New Tax Type Code Page")
      ("I am presented with the New Spr Duty Rate Page")
      ("I enter 11.5 on New Spr Duty Rate Page")
      ("I click save  continue button on New Spr Duty Rate Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click Volume on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment Volume With Spr Page with new url")
      ("I enter 4000.75 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 350.5500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 8.5 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the New Tax Type Code Page with new url")
      ("I enter 363 on New Tax Type Code Page")
      ("I click save  continue button on New Tax Type Code Page")
      ("I am presented with the New Spr Duty Rate Page with new url")
      ("I enter 11.5 on New Spr Duty Rate Page")
      ("I click save  continue button on New Spr Duty Rate Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click New SPR duty rate on Adjustment Check Your Answers Page")
      ("I am presented with the New Spr Duty Rate Page with new url")
      ("I enter 14.5 on New Spr Duty Rate Page")
      ("I click save  continue button on New Spr Duty Rate Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click New tax type on Adjustment Check Your Answers Page")
      ("I am presented with the New Tax Type Code Page with new url")
      ("I enter 313 on New Tax Type Code Page")
      ("I click save  continue button on New Tax Type Code Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button No on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Task List Page")
    }

    Scenario("4 Adjustments Journey - Changing Non SPR to SPR - Drawback - Spirits") {
      ("I select radio button Drawback on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page")
      ("I enter month 10  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code Page")
      ("I enter 315 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume Page")
      ("I enter 3000.75 for Total Litres on Adjustment Volume Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume Page")
      ("I click save  continue button on Adjustment Volume Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click Tax type on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment Tax Type Code Page with new url")
      ("I enter 375 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume With Spr Page with new url")
      ("I enter 3000.75 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 9.8 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button No on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Task List Page")
    }

    Scenario("5- Adjustments Journey - Change SPR to Non SPR - Drawback - Other Fermented Products") {
      ("I select radio button Drawback on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page")
      ("I enter month 10  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code Page")
      ("I enter 374 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume With Spr Page")
      ("I enter 3000.75 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 9.8 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click Tax type on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment Tax Type Code Page with new url")
      ("I enter 314 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume Page with new url")
      ("I enter 3000.75 for Total Litres on Adjustment Volume Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume Page")
      ("I click save  continue button on Adjustment Volume Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button No on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Task List Page")
    }

    Scenario("6 Adjustments Journey - Change Link Functionality - Spoilt - Spirits") {
      ("I select radio button Spoilt on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Spoilt Alcohol Type Page")
      ("I select radio button Spirits on Spoilt Alcohol Type Page")
      ("I click save  continue button on Spoilt Alcohol Type Page")
      ("I am presented with the Spoilt Alcohol Volume Page")
      ("I enter 3000.75 for Total Litres on Spoilt Alcohol Volume Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Spoilt Alcohol Volume Page")
      ("I enter 3255.55 for Duty Paid on Spoilt Alcohol Volume Page")
      ("I click save  continue button on Spoilt Alcohol Volume Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click Description on Adjustment Check Your Answers Page")
      ("I am presented with the Spoilt Alcohol Type Page with new url")
      ("I select radio button Beer on Spoilt Alcohol Type Page")
      ("I click save  continue button on Spoilt Alcohol Type Page")
      ("I am presented with the Spoilt Beer Alcohol Volume Page")
      ("I enter 3000.75 for Total Litres on Spoilt Beer Alcohol Volume Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Spoilt Beer Alcohol Volume Page")
      ("I enter 3255.55 for Duty Paid on Spoilt Beer Alcohol Volume Page")
      ("I click save  continue button on Spoilt Beer Alcohol Volume Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click Duty value on Adjustment Check Your Answers Page")
      ("I am presented with the Spoilt Beer Alcohol Volume Page with new url")
      ("I enter 3222.75 for Total Litres on Spoilt Beer Alcohol Volume Page")
      ("I enter 255.5500 for Litres Of Pure Alcohol on Spoilt Beer Alcohol Volume Page")
      ("I enter 3200.55 for Duty Paid on Spoilt Beer Alcohol Volume Page")
      ("I click save  continue button on Spoilt Beer Alcohol Volume Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button No on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Task List Page")
    }
  }
}
