import org.scalatest.matchers.should.Matchers
import org.scalatest.featurespec.AnyFeatureSpec

class AdjustmentsJourneyHappyPathSpec extends AnyFeatureSpec with Matchers {

  Feature("Adjustments Journey") {

    Scenario("Adjustments Journey - Validating under-declaration-reason removal from task List page  amount is changed to less than £1000 - Under-declaration - Beer - With SPR") {
      ("I select radio button Under-declaration on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page")
      ("I enter month 09  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code Page")
      ("I enter 371 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume With Spr Page")
      ("I enter 3000.75 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 250.5500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 9.8 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button No on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Task List Page")
      ("I click on Tell us why products were under-declared hyperlink on Task List Page")
      ("I am presented with the Under Declaration Reason Page")
      ("I enter Test Under Declaration Reason on Under Declaration Reason Page")
      ("I click save  continue button on Under Declaration Reason Page")
      ("I am presented with the Task List Page")
      ("I click on Declare adjustments hyperlink on Task List Page")
      ("I am presented with the Adjustment List Page")
      ("I click Change Hyperlink on Adjustment List Page")
      ("I am presented with the Adjustment Check Your Answers Page with new url")
      ("I click Volume on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment Volume With Spr Page with new url")
      ("I enter 2000.55 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 100.2500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 6.50 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button No on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Task List Page")
    }

    Scenario("Adjustments Journey - Validating over-declaration-reason removal from task List page  amount is changed to less than £1000 after deleting one of the adjustment- Over-declaration - Cider - With SPR") {
      ("I select radio button Over-declaration on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page")
      ("I enter month 10  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code Page")
      ("I enter 372 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume With Spr Page")
      ("I enter 1000.75 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 150.5500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 4.5 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button Yes on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Adjustment Type Page")
      ("I select radio button Over-declaration on Adjustment Type Page")
      ("I click save  continue button on Adjustment Type Page")
      ("I am presented with the Adjustment Return Date Page")
      ("I enter month 10  year 2023 on Adjustment Return Date Page")
      ("I click save  continue button on Adjustment Return Date Page")
      ("I am presented with the Adjustment Tax Type Code Page")
      ("I enter 372 on Adjustment Tax Type Code Page")
      ("I click save  continue button on Adjustment Tax Type Code Page")
      ("I am presented with the Adjustment Volume With Spr Page")
      ("I enter 1000.75 for Total Litres on Adjustment Volume With Spr Page")
      ("I enter 150.5500 for Litres Of Pure Alcohol on Adjustment Volume With Spr Page")
      ("I enter 4.5 for SPR Duty Rate on Adjustment Volume With Spr Page")
      ("I click save  continue button on Adjustment Volume With Spr Page")
      ("I am presented with the Adjustment Duty Value Page")
      ("I click continue button on Adjustment Duty Value Page")
      ("I am presented with the Adjustment Check Your Answers Page")
      ("I click save  continue button on Adjustment Check Your Answers Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button No on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Task List Page")
      ("I click on Tell us why products were over-declared hyperlink on Task List Page")
      ("I am presented with the Over Declaration Reason Page")
      ("I enter Test over Declaration Reason on Over Declaration Reason Page")
      ("I click save  continue button on Over Declaration Reason Page")
      ("I am presented with the Task List Page")
      ("I click on Declare adjustments hyperlink on Task List Page")
      ("I am presented with the Adjustment List Page")
      ("I click Remove Hyperlink on Adjustment List Page")
      ("I am presented with the Remove Adjustment Page")
      ("I select radio button No on Remove Adjustment Page")
      ("I click save  continue button on Remove Adjustment Page")
      ("I am presented with the Adjustment List Page")
      ("I click Remove Hyperlink on Adjustment List Page")
      ("I am presented with the Remove Adjustment Page")
      ("I select radio button Yes on Remove Adjustment Page")
      ("I click save  continue button on Remove Adjustment Page")
      ("I am presented with the Adjustment List Page")
      ("I select radio button No on Adjustment List Page")
      ("I click save  continue button on Adjustment List Page")
      ("I am presented with the Task List Page")
    }
  }
}
